artifacts_root: "artifacts"

data_ingestion:
  root_dir: "artifacts/01_data_ingestion"
  local_data_file: "notebooks/data/01_train.csv"
  raw_data_file: "artifacts/01_data_ingestion/raw_data.csv"
  src_chatwords_file: "notebooks/data/chatwords.yaml"
  dest_chatwords_file: "artifacts/01_data_ingestion/chatwords.yaml"

data_preprocessing:
  root_dir: "artifacts/02_preprocessed_data"
  raw_data_file: "artifacts/01_data_ingestion/raw_data.csv"
  chatwords_file: "artifacts/01_data_ingestion/chatwords.yaml"
  preprocessed_data: "artifacts/02_preprocessed_data/preprocessed_data.csv"

data_processing:
  root_dir: "artifacts/03_processed_data"
  preprocessed_data: "artifacts/02_preprocessed_data/preprocessed_data.csv"
  y_path: "artifacts/03_processed_data/y.csv"
  q1_encoded: "artifacts/03_processed_data/01_q1_encoded.csv"
  q2_encoded: "artifacts/03_processed_data/01_q2_encoded.csv"
  base_emb_model: "artifacts/04_models/01_base_emb_model.h5"
  trained_emb_model: "artifacts/04_models/02_trained_emb_model.h5"
  word_pair_emb: "artifacts/03_processed_data/02_word_pair_emb.csv"
  emb_matrix: "artifacts/03_processed_data/03_emb_matrix.csv"
  q1_emb: "artifacts/03_processed_data/04_q1_emb.csv"
  q2_emb: "artifacts/03_processed_data/04_q2_emb.csv"

prepare_base_model:
  root_dir: "artifacts/04_models"
  base_model: "artifacts/04_models/03_base_model.h5"
  
training:
  root_dir: "artifacts/05_training"
  trained_model: "artifacts/04_models/04_trained_model.h5"
  val_report: "artifacts/05_training/validation_report.yaml"

evaluation:
  root_dir: "artifacts/06_evaluation"
  test_dir: "artifacts/01_data_ingestion/test.csv"
  evaluation_report: "artifacts/06_evaluation/evaluation_report.yaml"
  mlflow_uri: "http://localhost:5000"