artifacts_root: "artifacts"

data_ingestion:
  root_dir: "artifacts/01_data_ingestion"
  local_data_file: "notebooks/data/01_train.csv"
  raw_data_file: "artifacts/01_data_ingestion/raw_data.csv"
  src_chatwords_file: "notebooks/data/chatwords.yaml"
  dest_chatwords_file: "artifacts/01_data_ingestion/chatwords.yaml"

data_preprocessing:
  root_dir: "artifacts/02_preprocessed_data"
  raw_data_file: "artifacts/01_data_ingestion/raw_data.csv"
  chatwords_file: "artifacts/01_data_ingestion/chatwords.yaml"
  preprocessed_data: "artifacts/02_preprocessed_data/preprocessed_data.csv"
  X_path: "artifacts/02_preprocessed_data/X.csv"
  y_path: "artifacts/02_preprocessed_data/y.csv"

data_processing:
  root_dir: "artifacts/03_processed_data"
  model_dir: "artifacts/04_models"
  X_path: "artifacts/02_preprocessed_data/X.csv"
  trained_emb_model: "artifacts/04_models/02_own_trained_emb_model.h5"
  bert_emb_model: "artifacts/04_models/03_bert_emb_model.h5"
  word_pair_emb: "artifacts/03_processed_data/02_word_pair_emb.csv"
  emb_matrix: "artifacts/03_processed_data/03_emb_matrix.csv"
  emb_data_own: "artifacts/03_processed_data/04_emb_data_own.csv"
  q1_emb_own: "artifacts/03_processed_data/04_q1_emb_own.npy"
  q2_emb_own: "artifacts/03_processed_data/04_q2_emb_own.npy"
  emb_data_bert: "artifacts/03_processed_data/05_emb_data_bert.csv"
  q1_emb_bert: "artifacts/03_processed_data/05_q1_emb_bert.npy"
  q2_emb_bert: "artifacts/03_processed_data/05_q2_emb_bert.npy"
  
training:
  root_dir: "artifacts/05_training"
  model_dir: "artifacts/04_models"
  y_path: "artifacts/02_preprocessed_data/y.csv"
  emb_matrix: "artifacts/03_processed_data/emb_matrix.csv"
  emb_data_own: "artifacts/03_processed_data/04_emb_data_own.csv"
  q1_emb_own: "artifacts/03_processed_data/04_q1_emb_own.npy"
  q2_emb_own: "artifacts/03_processed_data/04_q2_emb_own.npy"
  emb_data_bert: "artifacts/03_processed_data/05_emb_data_bert.csv"
  q1_emb_bert: "artifacts/03_processed_data/05_q1_emb_bert.npy"
  q2_emb_bert: "artifacts/03_processed_data/05_q2_emb_bert.npy"
  trained_model_with_own_emb: "artifacts/04_models/05_trained_model_with_own_emb.h5"
  trained_model_with_bert_emb: "artifacts/04_models/05_trained_model_with_bert_emb.h5"
  own_val_report: "artifacts/05_training/own_val_report.json"
  bert_val_report: "artifacts/05_training/bert_val_report.json"

evaluation:
  root_dir: "artifacts/06_evaluation"
  test_dir: "artifacts/01_data_ingestion/test.csv"
  evaluation_report: "artifacts/06_evaluation/evaluation_report.yaml"
  mlflow_uri: "http://localhost:5000"